plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.akmal.flowe'
version = '0.1.0'

android {
  namespace "expo.modules.flowenotifications"
  defaultConfig {
    versionCode 1
    versionName '0.1.0'
  }
}

dependencies {
  api "androidx.annotation:annotation:1.0.0"
}
